server:
  port: 8087
  servlet:
    context-path: /aswit
app:
  version: @version@
  public:
    path: /api
spring:
  mail:
    host: ssl0.ovh.net
    port: 587
    username: rejestracja@aswit.pl
    password: hEgFrPiz16N3n15KtLjS
  application:
    name: cs_pl
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://217.182.75.190:3309/aswit
    username: aswit
    password: hHGn6nveOwCn3w2uUKyG
    driver-class-name: org.mariadb.jdbc.Driver
