server:
  port: 8087
  servlet:
    context-path: /aswit
app:
  version: @version@
  public:
    path: /api
spring:
  mail:
    host: ssl0.ovh.net
    port: 587
    username: rejestracja@aswit.pl
    password: hEgFrPiz16N3n15KtLjS
  application:
    name: cs_pl
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://217.182.75.190:3309/aswit
    username: aswit
    password: hHGn6nveOwCn3w2uUKyG
    driver-class-name: org.mariadb.jdbc.Driver
keycloak:
  realm: Aswit
  auth-server-url: http://217.182.75.190:8081/auth
  ssl-required: none
  resource: aswit-be
  credentials:
    secret: 5eDiRLQiYlSyhvQ1P70VaWmt2pajnxZ4
  bearer-only: true
  use-resource-role-mappings: true
logging:
  level:
    pl:
      aswit:
        rest:
          client:
            KeycloakFeignClient: DEBUG
#    root: TRACE

