server:
  port: 8085
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
    context-path: /starter
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  server:
    port: 9085
    servlet:
      context-path: /
app:
  version: @version@
spring:
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_absent
  application:
    name: Portal Starter
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  session:
    store-type: none
  cache:
    jcache:
      config: classpath:ehcache.xml
  sleuth:
    sampler:
      probability: ${ZIPKIN_SAMPLER_PROBABILITY:1}
    feign:
      enabled: true
      processor:
        enabled: true
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    baseUrl: ${ZIPKIN_URL:http://0.0.0.0}
    service:
      name: STARTER
  aop:
    proxy-target-class: false
pru:
  servlet:
    pub-api-path: /api
    prv-api-path: /
  ap:
    rest:
      basePath: ${pru.servlet.pub-api-path}
    translations:
      ords:
        url: ${TRANSLATIONS_URL}
        log-level: basic
  cas:
    name: STARTER
    routing:
      session:
        url: ${CAS_SESSION_URL}
      pruuser:
        url: ${PRUUSER_URL}
    rest:
      basePath: ${pru.ap.rest.basePath}
logging:
  level:
    com:
      pru:
        ap:
          translations:
            provider:
              TranslationsOrdsClient: DEBUG
        cas:
          sso:
            provider:
              session:
                SessionManagerClient: DEBUG
              pruuser:
                PruUserClient: DEBUG
